spring:
  config:
    activate:
      on-profile:
        - prod
  datasource:
    schema:
      - classpath:schema.sql
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/subway?useSSL=false&ServerTimezone=UTC
    username: produser
    password: prod
